server:
    port: 9000

spring:
    application:
        name: H-GabrielGutierrez
    data:
        mongodb:
            uri: mongodb+srv://gabrielgutierrezq:rlM9Eq5qjWA7S268@artemio.uowgugn.mongodb.net/ARTEMIO?retryWrites=true&w=majority

external:
  api:
    url: https://jsonplaceholder.typicode.com

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000